export const products = [
  {
    id: 1,
    slug: "flowline-dresses",
    name: "Flowline Dresses",
    category: "Women",
    image: "/images/products/flowline-dresses.jpg",
    minPrice: 200,
    maxPrice: 250,
    colors: ["#7C3AED", "#16A34A", "#CA8A04"],
    sizes: ["M", "L", "XL"],
    onSale: false,
  },
  {
    id: 2,
    slug: "essential-polos",
    name: "Essential Polos",
    category: "Men",
    image: "/images/products/essential-polos.jpg",
    minPrice: 80,
    maxPrice: 90,
    colors: ["#6B7280", "#4B5563", "#9CA3AF"],
    sizes: ["M", "L", "XL"],
    onSale: false,
  },
  {
    id: 3,
    slug: "cream-t-shirt",
    name: "Cream T-Shirt",
    category: "Men",
    image: "/images/products/cream-tshirt.jpg",
    minPrice: 60,
    maxPrice: 65,
    colors: ["#E5E7EB", "#D1FAE5", "#BBF7D0"],
    sizes: ["M", "L", "XL"],
    onSale: true,
  },
  {
    id: 4,
    slug: "t-jacket-combo",
    name: "T Jacket Combo",
    category: "Men",
    image: "/images/products/t-jacket-combo.jpg",
    minPrice: 200,
    maxPrice: 210,
    colors: ["#FCD34D", "#86EFAC", "#6EE7B7"],
    sizes: ["M", "L", "XL"],
    onSale: true,
  },
  {
    id: 5,
    slug: "summer-t-shirt",
    name: "Summer T-Shirt",
    category: "Women",
    image: "/images/products/summer-tshirt.jpg",
    minPrice: 130,
    maxPrice: 135,
    colors: ["#7C3AED", "#1D4ED8", "#0F766E"],
    sizes: ["S", "M", "L"],
    onSale: false,
  },
  {
    id: 6,
    slug: "princess-hoodie",
    name: "Princess Hoodie",
    category: "Men",
    image: "/images/products/princess-hoodie.jpg",
    minPrice: 130,
    maxPrice: 140,
    colors: ["#E5E7EB", "#D1D5DB", "#9CA3AF"],
    sizes: ["XS", "S", "M"],
    onSale: false,
  },
  {
    id: 7,
    slug: "solid-shirt",
    name: "Solid Shirt",
    category: "Men",
    image: "/images/products/solid-shirt.jpg",
    minPrice: 80,
    maxPrice: 85,
    colors: ["#BFDBFE", "#93C5FD", "#60A5FA"],
    sizes: ["M", "L", "XL"],
    onSale: true,
  },
  {
    id: 8,
    slug: "mini-jackets",
    name: "Mini Jackets",
    category: "Kids",
    image: "/images/products/mini-jackets.jpg",
    minPrice: 150,
    maxPrice: 160,
    colors: ["#1F2937", "#374151", "#4B5563"],
    sizes: ["XS", "S", "M"],
    onSale: false,
  },
  {
    id: 9,
    slug: "funky-hoodie",
    name: "Funky Hoodie",
    category: "Kids",
    image: "/images/products/funky-hoodie.jpg",
    minPrice: 120,
    maxPrice: 125,
    colors: ["#F3F4F6", "#E5E7EB", "#D1D5DB"],
    sizes: ["XS", "S", "M"],
    onSale: true,
  },
];

export const testimonials = [
  { name: "Jessica M., San Diego", avatar: "avatar-jessica.jpg", quote: "Velora has completely transformed how I shop for clothes. Every piece feels thoughtfully designed and incredibly comfortable — from their polos to their jackets, it's the style, and quality right every single time." },
  { name: "Darren L., New York", avatar: "avatar-darren.jpg", quote: "I'm always looking for clean, versatile styles I can wear to work or on weekends — and Velora delivers. I picked up a few items from their collection and was blown away by the craftsmanship. The trousers, especially, have become my go-to." },
  { name: "Michelle T., Chicago", avatar: "avatar-michelle.jpg", quote: "Shopping for myself and my daughter usually means bouncing between stores, but Velora made it easy. I loved the quality of the dresses I ordered, and my daughter adored her Mini Jackets. Comfortable, well built — both fans for life!" },
];